#!/bin/bash

# LLM Training Project - Complete Setup and Training Script
# This script guides you through the entire process

echo "=================================================="
echo "🚀 GPT Language Model Training - Setup Guide"
echo "=================================================="
echo ""

# Check Python
echo "✓ Python environment configured"
echo "✓ All dependencies installed"
echo ""

# Display model info
echo "📊 Your Model Configuration:"
echo "  • Parameters: 124.24M (similar to GPT-2 Small)"
echo "  • Architecture: 12 layers, 12 heads, 768 dimensions"
echo "  • Optimized for: Mac M4 with MPS acceleration"
echo ""

echo "=================================================="
echo "📋 Three Simple Steps to Train Your LLM"
echo "=================================================="
echo ""

echo "STEP 1: Download Dataset"
echo "------------------------"
echo "Run: python src/data/download_dataset.py"
echo ""
echo "This will:"
echo "  • Download LLM-7 prompt dataset from Kaggle"
echo "  • Preprocess and split data (train/val/test)"
echo "  • Save to data/processed/"
echo ""
echo "Note: You'll need Kaggle credentials configured"
echo "      See QUICKSTART.md for setup instructions"
echo ""

echo "STEP 2: Train the Model"
echo "-----------------------"
echo "Run: python train.py"
echo ""
echo "This will:"
echo "  • Train BPE tokenizer (first run)"
echo "  • Initialize GPT model (124M parameters)"
echo "  • Train for 10 epochs with MPS acceleration"
echo "  • Save checkpoints to checkpoints/"
echo "  • Save best model based on validation loss"
echo ""
echo "Expected training time: 2-8 hours (depending on dataset size)"
echo ""

echo "STEP 3: Generate Text"
echo "---------------------"
echo "Run: python generate.py --interactive"
echo ""
echo "Or try:"
echo "  python generate.py --prompt 'Your prompt here'"
echo ""
echo "This will:"
echo "  • Load your trained model"
echo "  • Generate text from prompts"
echo "  • Support interactive mode for experimentation"
echo ""

echo "=================================================="
echo "📚 Documentation Files"
echo "=================================================="
echo ""
echo "  README.md         - Project overview"
echo "  QUICKSTART.md     - Quick start guide"
echo "  DOCUMENTATION.md  - Complete documentation"
echo "  requirements.txt  - Python dependencies"
echo ""

echo "=================================================="
echo "🛠️ Utility Commands"
echo "=================================================="
echo ""
echo "  python test_setup.py    - Verify installation"
echo "  python model_info.py    - Display model details"
echo ""

echo "=================================================="
echo "🎯 Ready to Start!"
echo "=================================================="
echo ""
echo "Begin with:"
echo "  python src/data/download_dataset.py"
echo ""
echo "Need help? Check QUICKSTART.md or DOCUMENTATION.md"
echo ""
echo "Good luck training your LLM! 🎉"
echo ""
